### POST OR REMOVE LIKEPOST http://localhost:8080/api/v1/video-like/close/create/like/1Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTMwNjU3MzEsImVtYWlsIjoibXlzaHVrdXJvdkBnbWFpbC5jb20iLCJleHAiOjE2OTM5Mjk3MzEsImlzcyI6IllPVVRVQkUgUE9SVEFMIn0.I7aGqkuiHUK9HJTFmOHrMSlbfs9ryNhubPKobMmwDYR-N-ztjjGbnzADIKYEANkeo3DMt71WL5xO89SpssdZrw### POST OR REMOVE DISLIKEPOST http://localhost:8080/api/v1/video-like/close/create/dislike/1Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTMwNjU3MzEsImVtYWlsIjoibXlzaHVrdXJvdkBnbWFpbC5jb20iLCJleHAiOjE2OTM5Mjk3MzEsImlzcyI6IllPVVRVQkUgUE9SVEFMIn0.I7aGqkuiHUK9HJTFmOHrMSlbfs9ryNhubPKobMmwDYR-N-ztjjGbnzADIKYEANkeo3DMt71WL5xO89SpssdZrw